### ISSUE TITLE
Readme doesn't cover what radio(s) this work on

### ISSUE THREAD

**Issue by Funcan** [M17-Project/Micro17#4]
Came here after a hackaday lightening talk, thought it looked like an interesting project to kick me into dusting off my ham license, but it doesn't tell me what radio to go scour eBay for.

I'm sure it's in here somewhere, but it would be great if it was in the readme I think for newcomers to the project

**Comment by ManoDaSilva** [comment]
Hey! Thanks for looking us up! Yes sorry this is still quite recent, we'll update the repo in the coming days. In the meantime, you'll find a more general list of compatible radios for Module17 use here:
https://wiki.m17project.org/radio_compatibility

Once micro17 is completely validated, I'll make a complete guide for programming and getting it running in those ICOM radios. In the meantime, the general radio compatibility list links to a page listing the "hacks" I presented in the Lightning talk: https://wiki.m17project.org/icf5060_3060

Cheers!

**Comment by ManoDaSilva** [comment]
Ah yeah, we also have a Discord if you'd rather use it: https://discord.gg/G8zGphypf6

**Comment by sp5wwp** [comment]
The Project's homepage needs major rework too.

**Comment by ManoDaSilva** [comment]
#6

**Comment by sp5wwp** [comment]
Fixed. :)
